basePath: /
definitions:
  params.ServerTimeRsp:
    properties:
      server_time:
        description: 服务器试卷
        type: integer
    type: object
host: localhost:16888
info:
  contact:
    email: svinsight@svinsight.com
    name: svinsight API Support
    url: http://www.svinsight.com
  description: pub开头的api不需要登录就可访问，pri开头的需要登录才能访问，访问pri开头的路由时，需要把登录返回的token放到header
    X-Token中，服务端会做鉴权。返回结果为json格式，包含字段code，data，msg三个字段 , 成功时，code为0，data有数据；失败时，code不为0，msg为错误消息。
  license:
    name: private
    url: http://www.svinsight.com/licenses/private.html
  termsOfService: http://swagger.io/terms/
  title: 智谷星图考试系统 API
  version: "1.0"
paths:
  /v1/pub/servertime:
    get:
      consumes:
      - application/json
      description: 获取服务器时间
      operationId: GetServerTime
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/params.ServerTimeRsp'
      summary: 获取服务器时间
      tags:
      - 用户
swagger: "2.0"
