############################################################################
# 通用配置段
[common]
# web服务器监听端口
port = 16888
# 是否启用性能分析，默认不启用
pprof = false


############################################################################
# 日志文件配置段
[log]
# 指定日志文件名，不指定或为空则用程序名做日志
file = "acg.log"
# 指定日志级别
level = "debug"
# 单个文件最大大小，单位MB
maxSize = 100
# 单个文件的最大存活时间，天数
maxAge = 7
# 最多保留多少个文件
maxBackup = 7


############################################################################
# database配置段
[database]
# gorm支持的数据库类型，sqlite,mysql,postgres
#driver = "sqlite"
driver = "mysql"
# 数据源
source = "root:betterjun@tcp(127.0.0.1:3306)/cg?charset=utf8&parseTime=True&loc=Local&timeout=5000ms"
#source = "./local.db"


############################################################################
# redis配置段
[redis]
# 数据库地址
redis_host = "127.0.0.1:6379"
# 数据库用户密码
redis_auth = "zj"
# 数据库
redis_db=121
# 最大连接数
redis_max_active=30
# 最大空闲数
redis_max_idle=30
# 空闲超时重连，单位秒
redis_idle_timeout=200


